[package]
name = "lru_macro"
version = "0.1.0"
authors = ["Mårten Nilsson <m@martennilsson.se>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.14.4", features = ["full"] }
quote = "0.6.3"
